### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [davidvavra/GPS-Averaging#7]
Would you consider publishing the `.apk` of your app at Github (preferably under `releases/`), so folks without GApps (and thus without Google Play) could get hold of it? Thanks in advance!

**Comment by davidvavra** [comment]
Sorry, I don't wish to support users without Google Play. You can use some service which downloads APKs from Google Play.

**Comment by IzzySoft** [comment]
Ump. OK, I respect that; but mind to give a reason, so I also can *understand* it? You certainly don't mean it that way, but as you've phrased it it almost sounds like a "personal vendetta" (a la "if you don't use Google Play you're my enemy" ;)

Btw: Thanks for the fast reply!

**Comment by davidvavra** [comment]
No vendetta :) Nothing personal against people who don't use Google Play. But they are minority and it's too much hassle maintaining more distribution channels for such a simple app.

**Comment by IzzySoft** [comment]
Glad to read it's not that :) Still, a simple upload to Github wouldn't be that much hassle. Consider the two fractions: one that *cannot* use GApps due to "local restrictions" (internet censorship), and the other that *does not want to* for privacy reasons (I belong into the latter). The cat's playing with its tail here on the second group: many people who consider "going Google-free for more privacy" don't do because they're bound to Play Store for their favorite apps – and devs stick to Play Store because people are (still) there.

So how often do you release, that an upload here would be so much hassle? ;) With the file available via Github, I'd take care for updating it [via an F-Droid repo](https://android.izzysoft.de/repo).

Of course I respect a "No". But given the little effort needed, that would be a pity.

**Comment by IzzySoft** [comment]
@davidvavra Have you maybe changed your mind? For one, I still didn't give up – and for the other, neither did others: someone [requested having your app added to F-Droid](https://gitlab.com/fdroid/rfp/issues/1005) (the official repo). F-Droid would build directly from the source, so no extra hassle for you with providing the APK "somewhere else".

That OK with you?

**Comment by davidvavra** [comment]
Hi I just sold the app, so you should ask new owners.

**Comment by IzzySoft** [comment]
Thanks for letting us know! Who would that be then? Currently it's still you who's marked "owner" here. Will the new owner keep the app open source and use this repo (or have they forked it), if you know?

**Comment by davidvavra** [comment]
I don't think the new owner will keep their changes open-source. This repo will contain original version of the code. You can contact new owner here: geka70911@gmail.com

**Comment by IzzySoft** [comment]
Thanks David! I've told the requestor to ask the new owner then. Would be a real pity if the answer were "no": many of us privacy-focused users (myself included) rather avoid Play Store and stick to FOSS apps from F-Droid.

All the best for your future projects then – and thanks for your support!
